/* PRODIO.H
*/

/* This file was assumed to exist. A real example on an original Sierra game disk
** has not been found. If this file is currently void of code, then it exists 
** merely as a placeholder to indicate that Siera's AGI interpreter had such a 
** file. If this file contains code, then it is because an attempt has been made
** to reconstruct what it might have looked like using a disassembly tool.
*/
