/* KEYDEFS.H
** Key code definitions
*/


#define	ctrl(c)	c - '@'

#define	CANCEL	ctrl('C')
#define	ECHO		ctrl('E')
#define	ADDJOY	ctrl('J')
#define	NEWPRMPT	ctrl('P')
#define	TGLRGB	ctrl('R')
#define	TGLSOUND	ctrl('S')
#define	SWIM		'='
#define	SHOWSTAT	'\t'

#define	UPARW	0x4800
#define	DNARW	0x5000
#define	LFTARW	0x4b00
#define	RGHTARW	0x4d00
#define	HOME		0x4700
#define	PGUP		0x4900
#define	END		0x4f00
#define	PGDN		0x5100
#define	CTRLLEFT	0x7300
#define	CTRLRGHT	0x7400
#define	CTRLPGDN	0x7600
#define	CTRLPGUP	0x8400
#define	F1		0x3b00
#define	F2		0x3c00
#define	F3		0x3d00
#define	F4		0x3e00
#define	F5		0x3f00
#define	F6		0x4000
#define	F7		0x4100
#define	F8		0x4200
#define	F9		0x4300
#define	F0		0x4400
#define	DEBUG	0x2000
